/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { CreateNewsletterSubscriptionRequestDto } from "../models/index";
import {
  CreateNewsletterSubscriptionRequestDtoFromJSON,
  CreateNewsletterSubscriptionRequestDtoToJSON,
} from "../models/index";

export interface CreateEmailSubscriptionRequest {
  createNewsletterSubscriptionRequestDto: CreateNewsletterSubscriptionRequestDto;
}

/**
 *
 */
export class NewsletterSubscriptionControllerApi extends runtime.BaseAPI {
  /**
   */
  async createEmailSubscriptionRaw(
    requestParameters: CreateEmailSubscriptionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["createNewsletterSubscriptionRequestDto"] == null) {
      throw new runtime.RequiredError(
        "createNewsletterSubscriptionRequestDto",
        'Required parameter "createNewsletterSubscriptionRequestDto" was null or undefined when calling createEmailSubscription().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/newsletter-subscription`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreateNewsletterSubscriptionRequestDtoToJSON(
          requestParameters["createNewsletterSubscriptionRequestDto"],
        ),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async createEmailSubscription(
    requestParameters: CreateEmailSubscriptionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.createEmailSubscriptionRaw(requestParameters, initOverrides);
  }
}
