/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateNewsletterSubscriptionRequestDto
 */
export interface CreateNewsletterSubscriptionRequestDto {
  /**
   *
   * @type {string}
   * @memberof CreateNewsletterSubscriptionRequestDto
   */
  email?: string;
}

/**
 * Check if a given object implements the CreateNewsletterSubscriptionRequestDto interface.
 */
export function instanceOfCreateNewsletterSubscriptionRequestDto(
  value: object,
): value is CreateNewsletterSubscriptionRequestDto {
  return true;
}

export function CreateNewsletterSubscriptionRequestDtoFromJSON(
  json: any,
): CreateNewsletterSubscriptionRequestDto {
  return CreateNewsletterSubscriptionRequestDtoFromJSONTyped(json, false);
}

export function CreateNewsletterSubscriptionRequestDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateNewsletterSubscriptionRequestDto {
  if (json == null) {
    return json;
  }
  return {
    email: json["email"] == null ? undefined : json["email"],
  };
}

export function CreateNewsletterSubscriptionRequestDtoToJSON(
  json: any,
): CreateNewsletterSubscriptionRequestDto {
  return CreateNewsletterSubscriptionRequestDtoToJSONTyped(json, false);
}

export function CreateNewsletterSubscriptionRequestDtoToJSONTyped(
  value?: CreateNewsletterSubscriptionRequestDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value["email"],
  };
}
