/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface NewsletterSubscription
 */
export interface NewsletterSubscription {
  /**
   *
   * @type {number}
   * @memberof NewsletterSubscription
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof NewsletterSubscription
   */
  email?: string;
}

/**
 * Check if a given object implements the NewsletterSubscription interface.
 */
export function instanceOfNewsletterSubscription(value: object): value is NewsletterSubscription {
  return true;
}

export function NewsletterSubscriptionFromJSON(json: any): NewsletterSubscription {
  return NewsletterSubscriptionFromJSONTyped(json, false);
}

export function NewsletterSubscriptionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NewsletterSubscription {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    email: json["email"] == null ? undefined : json["email"],
  };
}

export function NewsletterSubscriptionToJSON(json: any): NewsletterSubscription {
  return NewsletterSubscriptionToJSONTyped(json, false);
}

export function NewsletterSubscriptionToJSONTyped(
  value?: NewsletterSubscription | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    email: value["email"],
  };
}
